apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autosubs-storage
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.storage.size }}
  {{- if .Values.backend.storage.storageClass }}
  storageClassName: {{ .Values.backend.storage.storageClass }}
  {{- end }}
