apiVersion: v1
kind: Service
metadata:
  name: autosubs-frontend
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: autosubs-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082
